// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhAcmk8LN27tVzhAYhTkQNVD2H35jdGcE',
    appId: '1:146846686215:web:73660e8fc207599f8a5ea2',
    messagingSenderId: '146846686215',
    projectId: 'projet-4536c',
    authDomain: 'projet-4536c.firebaseapp.com',
    databaseURL: 'https://projet-4536c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-4536c.firebasestorage.app',
    measurementId: 'G-ENBY3K542X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGPQofl9Z8tYM7-ptFcQfz5dtqx4bekM',
    appId: '1:146846686215:android:ee9a19f28fd578778a5ea2',
    messagingSenderId: '146846686215',
    projectId: 'projet-4536c',
    databaseURL: 'https://projet-4536c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-4536c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmrlCpl7O30IDgZ-KXSefw0qVCSPpXg_4',
    appId: '1:146846686215:ios:4cd495e3d2a772538a5ea2',
    messagingSenderId: '146846686215',
    projectId: 'projet-4536c',
    databaseURL: 'https://projet-4536c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-4536c.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmrlCpl7O30IDgZ-KXSefw0qVCSPpXg_4',
    appId: '1:146846686215:ios:4cd495e3d2a772538a5ea2',
    messagingSenderId: '146846686215',
    projectId: 'projet-4536c',
    databaseURL: 'https://projet-4536c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-4536c.firebasestorage.app',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhAcmk8LN27tVzhAYhTkQNVD2H35jdGcE',
    appId: '1:146846686215:web:024dd0d3c27bbae48a5ea2',
    messagingSenderId: '146846686215',
    projectId: 'projet-4536c',
    authDomain: 'projet-4536c.firebaseapp.com',
    databaseURL: 'https://projet-4536c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-4536c.firebasestorage.app',
    measurementId: 'G-BDVZ66J9VL',
  );
}
