// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuerlkbL_gFGJZX6ep1LhnvLP0_LZ_4Rk',
    appId: '1:1078313432708:web:48177a9b9e1c7524d834d1',
    messagingSenderId: '1078313432708',
    projectId: 'contacts-app-27838',
    authDomain: 'contacts-app-27838.firebaseapp.com',
    databaseURL: 'https://contacts-app-27838-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-27838.firebasestorage.app',
    measurementId: 'G-ZHT38461CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwFZxbPMT1W0Ut2v83saTyqI3FXafTO8',
    appId: '1:1078313432708:android:ffa02f59b74621b9d834d1',
    messagingSenderId: '1078313432708',
    projectId: 'contacts-app-27838',
    databaseURL: 'https://contacts-app-27838-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-27838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD86BP0xvydnpRW50z-SPwFjKfwoDiQD98',
    appId: '1:1078313432708:ios:836ecf2b71bcc7f3d834d1',
    messagingSenderId: '1078313432708',
    projectId: 'contacts-app-27838',
    databaseURL: 'https://contacts-app-27838-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-27838.firebasestorage.app',
    androidClientId: '1078313432708-g8qic0qm88no0ekb2nlp5m2d05bm2mpj.apps.googleusercontent.com',
    iosClientId: '1078313432708-ej387h0d4242j9b9kpc22jigcf40hki3.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD86BP0xvydnpRW50z-SPwFjKfwoDiQD98',
    appId: '1:1078313432708:ios:836ecf2b71bcc7f3d834d1',
    messagingSenderId: '1078313432708',
    projectId: 'contacts-app-27838',
    databaseURL: 'https://contacts-app-27838-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-27838.firebasestorage.app',
    androidClientId: '1078313432708-g8qic0qm88no0ekb2nlp5m2d05bm2mpj.apps.googleusercontent.com',
    iosClientId: '1078313432708-ej387h0d4242j9b9kpc22jigcf40hki3.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuerlkbL_gFGJZX6ep1LhnvLP0_LZ_4Rk',
    appId: '1:1078313432708:web:c2ec47f871820667d834d1',
    messagingSenderId: '1078313432708',
    projectId: 'contacts-app-27838',
    authDomain: 'contacts-app-27838.firebaseapp.com',
    databaseURL: 'https://contacts-app-27838-default-rtdb.firebaseio.com',
    storageBucket: 'contacts-app-27838.firebasestorage.app',
    measurementId: 'G-10NF26YNZZ',
  );

}